# Generated by Django 6.0.3 on 2026-03-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Goalkeeper', 'Goalkeeper'), ('Sweeper', 'Sweeper'), ('Centre-back', 'Centre-back'), ('Full-back', 'Full-back'), ('Wing-back', 'Wing-back'), ('Defensive Midfielder', 'Defensive Midfielder'), ('Central Midfielder', 'Central Midfielder'), ('Attacking Midfielder', 'Attacking Midfielder'), ('Winger', 'Winger'), ('Forward', 'Forward'), ('Striker', 'Striker')], max_length=50),
        ),
    ]
